config/routes.rb
Rails.application.routes.draw do

  get 'subjects/new'

  root "static_pages#home"
  get "help" => "static_pages#help"
  get "contact" => "static_pages#contact"
  get "about"   => "static_pages#about"
  get "signup" => "users#new"
  get "login"  => "sessions#new"
  post "login"  => "sessions#create"
  delete "logout"  => "sessions#destroy"
  
  get "creatcourse" => "courses#new"
  get "courses/new"

  resources  :users
  resources  :courses
  resources  :subjects

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :supervisor_user, only: [:new , :create, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:index, :new, :create, :edit, :update, :destroy]

  def index
    @courses = Course.paginate(page: params["page"])
  end  
  
  def show
  	@course = Course.find(params[:id])
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)
    course_params[:info] = 1
    if @course.save
      flash[:success] = "Welcome to the new course!"
      redirect_to @course
    else
      render 'new'
    end
  end

  def edit
    @course = Course.find(params[:id])
    is_course_started(@course)
  end

  def update
    @course = Course.find(params[:id])
    if @course.update_attributes(course_params)
      flash[:success] = "Course update success"
      redirect_to courses_url
    else 
      render "edit"
    end
  end

  def destroy
    Course.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to courses_url
  end
private

    def course_params
      params.require(:course).permit(:name, :total_level, :info, :status)
    end

    def is_course_started(course)
      unless course.status == 1
        flash[:danger] = "Course have been started"
        redirect_to courses_url
      end
    end

    def supervisor_user
      if !current_user.is_supervisor?
        flash[:danger] = "Xin loi be khong co quyen nay ^_^ bye bye!"
        redirect_to root_url 
      end
    end

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

end

# cap id_supervisor

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_course.html.erb
<li>
  <%= link_to course.name, course %>  
  <% if current_user.is_supervisor? %>
  | <%= link_to "delete", course, method: :delete, data: { confirm: "You sure?" } %>
  | <%= link_to "edit", edit_course_path(course) %> 
  <% end %>
  <% if current_user.is_trainer? %>
  | <%= link_to "register","#" %>
  <% end %>
</li>

app/views/courses/edit.html.erb
<% provide(:title, 'Edit course') %>
<h1>Edit course</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@course) do |f| %>

    <%= render 'shared/course_error_messages', object: f.object  %>

     <%= f.label :name %>
     <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :total_level %>
      <%= f.number_field :total_level, class: 'form-control' %>

      <%= f.label :info %>
      <%= f.text_field :info, class: 'form-control'   %>

      <%= f.label :status %>
      <%= f.number_field :status, class: 'form-control' %>

      <%= f.submit "Edit course", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/courses/index.html.erb
<% provide(:title, 'All course') %>
<h1>All course</h1>
<% if current_user.is_supervisor? %>
<%= link_to "Create new course", creatcourse_path, class: "btn btn-lg btn-primary" %>
<% end %>
<%= will_paginate %>
<ul class="course">
  <%= render @courses %>
</ul>
<%= will_paginate %>

app/views/courses/new.html.erb
<% provide(:title, 'Creat course') %>
<h1>Create course</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@course) do |f| %>

    <%= render 'shared/error_messages', object: f.object  %>

     <%= f.label :name %>
     <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :total_level %>
      <%= f.number_field :total_level, class: 'form-control' %>

      <%= f.label :info %>
      <%= f.text_field :info, class: 'form-control' 	%>

      <%= f.label :status %>
      <%= f.number_field :status, class: 'form-control' %>

      <%= f.submit "Create new course", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/courses/show.html.erb
<% provide(:title, @course.name) %>
<h1>
  <%= @course.name %>
  <li><%= link_to "Edit course", edit_course_path(@course) %></li>
</h1>